linters:
  auto-fix: false
  enable:
    - deadcode
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
run:
  skip-dirs:
    - bin
    - dist

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  lll:
    line-length: 250
  dupl:
    threshold: 400
  goimports:
    local-prefixes: github.com/kensipe
issues:
  # ignore errchecks for test files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck